### ISSUE TITLE
the right syntax to use near 'json null' at line 1

### ISSUE THREAD

**Issue by daniels123kid** [luckyrabbitllc/StartupEngine#8]
![capture](https://user-images.githubusercontent.com/24682769/32694507-931143ba-c752-11e7-99ac-cdfd5423f94d.PNG)

am getting this error after db:seed and migration am using windows 7 with xampp server please help i have no idea with this error is coming from thanks for opensource-sing this application i think i would love to use it.

**Comment by luckyrabbitllc** [comment]
I think this is probably related to the fact that MySQL doesn't support the JSON column type. 

(see: https://stackoverflow.com/questions/44431314/json-datatype-in-not-available-in-xampp)

There are ways to build MySQL that support JSON, but I recommend using a PostgreSQL database. That's what we officially support, since that's what Heroku offers in their free tier.

Here's the installer for Windows.
https://www.postgresql.org/download/windows/

**Comment by daniels123kid** [comment]
I was trying to work out with postgres but it's quite new to me but at least thank you for your insights on the issue hope when I get to know more about it it will work thanks good luck Mr luckyrabbitllc

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
